import{a as p,S as L,i as d}from"./assets/vendor-95dc692e.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();async function h(r,e){p.defaults.baseURL="https://pixabay.com/api/";const n={key:"21675808-1204a02bf0a9f212ef3ae3caa",q:r,page:e,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:"true"},t=new URLSearchParams(n);return await p.get(`?${t}`).then(o=>o.data).catch(o=>console.log(o))}function g(r){return r.map(e=>`<li class="gallery-item">
                <a class="gallery-link" href='${e.largeImageURL}'>
                  <img class="gallery-image" src='${e.webformatURL}' alt='${e.tags}' />
                </a>
                <div class="stats">
                  <p><span>Likes</span>${e.likes}</p>
                  <p><span>Views</span>${e.views}</p>
                  <p><span>Comments</span>${e.comments}</p>
                  <p><span>Downloads</span>${e.downloads}</p>
                </div>
              </li>`).join("")}const b=document.querySelector(".form"),u=document.querySelector(".gallery"),y=document.querySelector(".loader"),l=document.querySelector(".load-more");b.addEventListener("submit",P);l.addEventListener("click",S);const v=new L(".gallery-link",{captionsData:"alt",captionDelay:250,overlay:!0,overlayOpacity:.7});let a=1,i="";function P(r){r.preventDefault(),l.classList.add("is-hidden"),m(),u.innerHTML="",a=1,i=r.target.queryInput.value.trim(),i!==""?h(i,a).then(e=>{if(e.hits.length===0)return d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});u.innerHTML=g(e.hits),e.total>15&&l.classList.remove("is-hidden"),v.refresh()}).catch(e=>{console.log(e)}).finally(()=>{f()}):(f(),d.info({message:'Please, enter a query, for example "cats"',position:"topLeft"})),r.currentTarget.reset()}function S(){m(),a+=1,h(i,a).then(r=>{const e=Math.ceil(r.total/15);u.insertAdjacentHTML("beforeend",g(r.hits));const{height:s}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"}),e===a&&(l.classList.add("is-hidden"),d.info({message:"We're sorry, but you've reached the end of search results.",position:"topLeft"}))}).catch(r=>{console.log(r)}).finally(()=>{f()})}function m(){y.classList.remove("is-hidden")}function f(){y.classList.add("is-hidden")}
//# sourceMappingURL=commonHelpers.js.map
