import{a as f,S as b,i as d}from"./assets/vendor-95dc692e.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();async function y(r,e){f.defaults.baseURL="https://pixabay.com/api/";const i={key:"21675808-1204a02bf0a9f212ef3ae3caa",q:r,page:e,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:"true"},t=new URLSearchParams(i),s=await f.get(`?${t}`);try{return s.data}catch(a){console.log(a)}}function g(r){return r.map(e=>`<li class="gallery-item">
                <a class="gallery-link" href='${e.largeImageURL}'>
                  <img class="gallery-image" src='${e.webformatURL}' alt='${e.tags}' />
                </a>
                <div class="stats">
                  <p><span>Likes</span>${e.likes}</p>
                  <p><span>Views</span>${e.views}</p>
                  <p><span>Comments</span>${e.comments}</p>
                  <p><span>Downloads</span>${e.downloads}</p>
                </div>
              </li>`).join("")}const v=document.querySelector(".form"),u=document.querySelector(".gallery"),h=document.querySelector(".loader"),c=document.querySelector(".load-more");v.addEventListener("submit",w);c.addEventListener("click",q);const m=new b(".gallery-link",{captionsData:"alt",captionDelay:250,overlay:!0,overlayOpacity:.7});let n=1,l="";async function w(r){if(r.preventDefault(),L(),c.classList.add("is-hidden"),u.innerHTML="",n=1,l=r.target.queryInput.value.trim(),l!==""){const e=await y(l,n);try{if(e.hits.length===0)return p(),d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});u.innerHTML=g(e.hits),e.total>15&&c.classList.remove("is-hidden"),m.refresh(),r.target.queryInput.value=""}catch(o){console.log(o)}}else d.info({message:'Please, enter a query, for example "cats"',position:"topLeft"});p()}async function q(){L(),n+=1;try{const r=await y(l,n),e=Math.ceil(r.total/15);u.insertAdjacentHTML("beforeend",g(r.hits)),m.refresh();const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),e===n&&(c.classList.add("is-hidden"),d.info({message:"We're sorry, but you've reached the end of search results.",position:"topLeft"}))}catch(r){console.log(r)}p()}function L(){h.classList.remove("is-hidden")}function p(){h.classList.add("is-hidden")}
//# sourceMappingURL=commonHelpers.js.map
