import{a as i,S as f,i as l}from"./assets/vendor-95dc692e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();async function d(a,t){i.defaults.baseURL="https://pixabay.com/api/";const s={key:"21675808-1204a02bf0a9f212ef3ae3caa",q:a,image_type:"photo",orientation:"horizontal",safesearch:"true"},e=new URLSearchParams(s);return await i.get(`?${e}`).then(r=>r.data).catch(r=>console.log(r))}function y(a){return a.map(t=>`<li class="gallery-item">
                <a class="gallery-link" href='${t.largeImageURL}'>
                  <img class="gallery-image" src='${t.webformatURL}' alt='${t.tags}' />
                </a>
                <div class="stats">
                  <p><span>Likes</span>${t.likes}</p>
                  <p><span>Views</span>${t.views}</p>
                  <p><span>Comments</span>${t.comments}</p>
                  <p><span>Downloads</span>${t.downloads}</p>
                </div>
              </li>`).join("")}const g=document.querySelector(".form"),c=document.querySelector(".gallery"),p=document.querySelector(".loader");g.addEventListener("submit",h);const m=new f(".gallery-link",{captionsData:"alt",captionDelay:250,overlay:!0,overlayOpacity:.7});function h(a){a.preventDefault(),L(),c.innerHTML="";const t=a.target.queryInput.value.trim();t!==""?d(t).then(o=>{if(o.hits.length===0)return l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});c.innerHTML=y(o.hits),m.refresh()}).catch(o=>{console.log(o)}).finally(()=>{u()}):(u(),l.error({message:'Please, enter a query, for example "cats"',position:"topRight"})),a.currentTarget.reset()}function L(){p.classList.remove("is-hidden")}function u(){p.classList.add("is-hidden")}
//# sourceMappingURL=commonHelpers.js.map
